# Generated by Django 4.2.1 on 2023-07-05 00:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_producto', models.IntegerField()),
                ('nombre', models.CharField(max_length=25)),
                ('marca', models.CharField(max_length=25)),
                ('descripcion', models.CharField(max_length=200)),
                ('talla', models.CharField(max_length=4)),
                ('precio', models.IntegerField()),
                ('stock', models.IntegerField()),
                ('id_categoria', models.ForeignKey(db_column='idCategoria', on_delete=django.db.models.deletion.CASCADE, to='venta.categoria')),
            ],
        ),
    ]
