# Generated by Django 4.2.1 on 2023-06-27 22:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id_categoria', models.BigAutoField(db_column='idCategoria', primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('username', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('rut', models.CharField(max_length=9)),
                ('pnombre', models.CharField(max_length=15)),
                ('snombre', models.CharField(blank=True, max_length=15, null=True)),
                ('appaterno', models.CharField(max_length=15)),
                ('apmaterno', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(max_length=60, unique=True)),
                ('contrasena', models.CharField(max_length=20)),
                ('direccion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.BigAutoField(db_column='idProducto', primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=25)),
                ('marca', models.CharField(max_length=25)),
                ('descripcion', models.CharField(max_length=200)),
                ('talla', models.CharField(max_length=4)),
                ('precio', models.IntegerField()),
                ('stock', models.IntegerField()),
                ('imagen', models.ImageField(null=True, upload_to='productos/')),
                ('id_categoria', models.ForeignKey(db_column='idCategoria', on_delete=django.db.models.deletion.CASCADE, to='venta.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id_pedido', models.BigAutoField(db_column='id_pedido', primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('total', models.IntegerField()),
                ('direccion', models.ForeignKey(db_column='direccion', on_delete=django.db.models.deletion.CASCADE, related_name='direccion_pedido', to='venta.cliente')),
                ('email_cliente', models.ForeignKey(db_column='email', on_delete=django.db.models.deletion.CASCADE, related_name='email_cliente', to='venta.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Boleta',
            fields=[
                ('id_boleta', models.BigAutoField(db_column='id_boleta', primary_key=True, serialize=False)),
                ('fecha', models.ForeignKey(db_column='fecha', on_delete=django.db.models.deletion.CASCADE, related_name='fecha_boleta', to='venta.pedido')),
                ('id_pedido', models.ForeignKey(db_column='id_pedido', on_delete=django.db.models.deletion.CASCADE, related_name='id_compra', to='venta.pedido')),
                ('total', models.ForeignKey(db_column='total', on_delete=django.db.models.deletion.CASCADE, related_name='total_boleta', to='venta.pedido')),
            ],
        ),
    ]
